---
- name: Determine available groups
  getent:
    database: group

- name: Determine available users
  getent:
    database: passwd

- name: Check if accountsservice is installed
  command: pacman -Q accountsservice
  register: accountsservice_installed
  failed_when: no
  changed_when: no

- name: Check if virtualbox-guest-utils is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_installed
  failed_when: no
  changed_when: no

- name: Check if virtualbox-guest-utils-nox is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_nox_installed
  failed_when: no
  changed_when: no
  
- name: Check if gdm is installed
  command: pacman -Q gdm
  register: gdm_installed
  failed_when: no
  changed_when: no
  
- name: setup labuser login screen
  copy:
    dest: /var/lib/AccountsService/users/labuser
    group: root
    owner: root
    mode: 600
    content: |
      [User]
      XSession=gnome
      SystemAccount=false
  when: (accountsservice_installed.rc == 0)

- name: make user
  vars:
    user_name: labuser
    # created with:
    # openssl passwd -salt saltysalt -1 change_me
    hashed_pw: $1$saltysal$26n01S/ZGnaY.LX7UxFfV/
  user:
    name: "{{ user_name }}"
    password: "{{ hashed_pw }}"
  when: user_name not in getent_passwd

- name: setup general purpose groups
  user:
    name: labuser
    append: yes
    groups: uucp,video,users,audio,tty

- name: add labuser to the aur group
  user:
    name: labuser
    append: yes
    groups: aur
  when: "aur" in getent_group
  
- name: add labuser to the vagrant group
  user:
    name: labuser
    append: yes
    groups: vagrant
  when: "vagrant" in getent_group
  
- name: add vagrant to the labuser group
  user:
    name: vagrant
    append: yes
    groups: labuser
  when: "vagrant" in getent_passwd

- name: add labuser to vbox group
  user:
    name: labuser
    append: yes
    groups: vboxsf
  when: virtualbox_guest_utils_nox_installed.rc == 0 or virtualbox_guest_utils_installed.rc == 0

- name: add labuser to autologin groups
  user:
    name: labuser
    append: yes
    groups: nopasswdlogin,autologin
  when: gdm_installed.rc == 0
  
- name: 5 second autologin timeout for labuser
  blockinfile:
    insertafter: '^\[daemon\]'
    path: /etc/gdm/custom.conf
    block: |
      TimedLogin=labuser
      TimedLoginEnable=True
      TimedLoginDelay=5
  when: ("/etc/gdm/custom.conf" is file)
  
- name: link in a pre-existing (or not), external config file
  file:
    state: link
    force: yes
    src: /vagrant/measurement_config.yaml
    path: ~/measurement_config.yaml
  become: yes
  become_user: labuser
  when: "vagrant" in getent_passwd
  #when: ("/vagrant/measurement_config.ini" is exists)

- name: link in a pre-existing (or not), external data folder
  file:
    force: yes
    state: link
    src: /vagrant/data
    path: ~/data
  become: yes
  become_user: labuser
  when: "vagrant" in getent_passwd
  #when: ("/vagrant/data" is exists) and (not ("/home/labuser/data" is exists))

#- name: make a data folder if needed
#  file:
#    state: directory
#    path: ~/data
#  become: yes
#  become_user: labuser
#  when: not ("/home/labuser/data" is exists)

- name: make user service folder
  file:
    state: directory
    path: ~/.config/systemd/user
  become: yes
  become_user: labuser

- name: make user enable service user folder
  file:
    state: directory
    path: ~/.config/systemd/user/default.target.wants
  become: yes
  become_user: labuser

- name: link user utility service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/utility-handler.service
    path: ~/.config/systemd/user/utility-handler.service
  become: yes
  become_user: labuser

- name: link in enabled user utility service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/utility-handler.service
    path: ~/.config/systemd/user/default.target.wants/utility-handler.service
  become: yes
  become_user: labuser

- name: link user plotter service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/plotter.service
    path: ~/.config/systemd/user/plotter.service
  become: yes
  become_user: labuser

- name: link in enabled user plotter service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/plotter.service
    path: ~/.config/systemd/user/default.target.wants/plotter.service
  become: yes
  become_user: labuser

- name: link user saver service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/saver.service
    path: ~/.config/systemd/user/saver.service
  become: yes
  become_user: labuser

- name: link in enabled user saver service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/saver.service
    path: ~/.config/systemd/user/default.target.wants/saver.service
  become: yes
  become_user: labuser

- name: link user run service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/run-handler.service
    path: ~/.config/systemd/user/run-handler.service
  become: yes
  become_user: labuser

- name: link in enabled user run service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/run-handler.service
    path: ~/.config/systemd/user/default.target.wants/run-handler.service
  become: yes
  become_user: labuser

- name: make autostart folder
  file:
    state: directory
    path: ~/.config/autostart
  become: yes
  become_user: labuser

- name: link in launcher autostart
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/control-ui/Control.desktop
    path: ~/.config/autostart/Control.desktop
  become: yes
  become_user: labuser

- name: make apps folder
  file:
    state: directory
    path: ~/.local/share/applications
  become: yes
  become_user: labuser

- name: link in launcher
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/control-ui/Control.desktop
    path: ~/.local/share/applications/Control.desktop
  become: yes
  become_user: labuser

#TODO: make favorite
