---
- name: Determine available groups
  getent:
    database: group

- name: Determine available users
  getent:
    database: passwd

- name: make user
  vars:
    # created with:
    # openssl passwd -salt saltysalt -1 change_me
    user_name: labuser
    hashed_pw: $1$saltysal$26n01S/ZGnaY.LX7UxFfV/
  user:
    name: "{{ user_name }}"
    password: "{{ hashed_pw }}"
  when: user_name not in getent_passwd

- name: setup groups
  user:
    name: labuser
    append: yes
    groups: wheel,uucp,video,users,audio,tty

- name: add labuser to the aur group
  user:
    name: labuser
    append: yes
    groups: aur
  when: getent_group['aur'] != none

- name: Check if virtualbox-guest-utils is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_installed
  failed_when: no
  changed_when: no

- name: Check if virtualbox-guest-utils-nox is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_nox_installed
  failed_when: no
  changed_when: no

- name: add labuser to vbox group
  user:
    name: labuser
    append: yes
    groups: vboxsf
  when: virtualbox_guest_utils_nox_installed.rc == 0 or virtualbox_guest_utils_installed.rc == 0

- name: Check if gdm is installed
  command: pacman -Q gdm
  register: gdm_installed
  failed_when: no
  changed_when: no

- name: add labuser to autologin groups
  user:
    name: labuser
    append: yes
    groups: nopasswdlogin,autologin
  when: gdm_installed.rc == 0
  
- name: 5 second autologin timeout for labuser
  blockinfile:
    insertafter: '^\[daemon\]'
    path: /etc/gdm/custom.conf
    block: |
      TimedLogin=labuser
      TimedLoginEnable=True
      TimedLoginDelay=5
  when: ("/etc/gdm/custom.conf" is file)

- name: give vagrant labuser group
  user:
    name: vagrant
    append: yes
    groups: labuser
  when: "'vagrant' in getent_passwd"

- name: link in a pre-existing, external config file
  file:
    state: link
    force: yes
    src: /vagrant/measurement_config.ini
    path: ~/measurement_config.ini
  become: yes
  become_user: labuser
  when: ("/vagrant/measurement_config.ini" is exists)

- name: link in a pre-existing, external data folder
  file:
    state: link
    src: /vagrant/data
    path: ~/data
  become: yes
  become_user: labuser
  when: ("/vagrant/data" is exists) and (not ("/home/labuser/data" is exists))

- name: make a data folder if needed
  file:
    state: directory
    path: ~/data
  become: yes
  become_user: labuser
  when: not ("/home/labuser/data" is exists)

- name: make user service folder
  file:
    state: directory
    path: ~/.config/systemd/user
  become: yes
  become_user: labuser

- name: link user in service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/utility-handler.service
    path: ~/.config/systemd/user/utility-handler.service
  become: yes
  become_user: labuser

- name: make user enable service user folder
  file:
    state: directory
    path: ~/.config/systemd/user/default.target.wants
  become: yes
  become_user: labuser

- name: link in enabled user service
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/central-control/config/utility-handler.service
    path: ~/.config/systemd/user/default.target.wants/utility-handler.service
  become: yes
  become_user: labuser

- name: make autostart folder
  file:
    state: directory
    path: ~/.config/autostart
  become: yes
  become_user: labuser

- name: link in launcher autostart
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/control-ui/Control.desktop
    path: ~/.config/autostart/Control.desktop
  become: yes
  become_user: labuser

- name: make apps folder
  file:
    state: directory
    path: ~/.local/share/applications
  become: yes
  become_user: labuser

- name: link in launcher
  file:
    state: link
    follow: no
    force: yes
    src: /opt/software/source/control-ui/Control.desktop
    path: ~/.local/share/applications/Control.desktop
  become: yes
  become_user: labuser

#TODO: make favorite
