---
- name: make tmp directory
  file:
    path: /tmp/ansible
    state: directory
    group: nobody
    mode: 0777

- name: Get the kernel version
  command: "uname -r"
  register: uname

- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: ensure we have some high level deps
  pacman:
    name: git bash-completion vi vim repo git-lfs inetutils python

#- name: give wheel group sudo powers
#  lineinfile:
#    path: /etc/sudoers
#    regexp: '^# %wheel ALL=(ALL) ALL'
#    line: '%wheel ALL=(ALL) ALL'
#    validate: /usr/sbin/visudo -cf %s

- name: give wheel group sudo powers
  lineinfile:
    backrefs: True
    path: /etc/sudoers
    regexp: '^# %wheel ALL=(ALL) ALL'
    replace: '%wheel ALL=(ALL) ALL'
    validate: /usr/sbin/visudo -cf %s
