---
- name: make tmp directory
  file:
    path: /tmp/ansible
    state: directory
    group: nobody
    mode: 0777

- name: Get the kernel version
  command: "uname -r"
  register: uname

- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: ensure we have some high level deps
  pacman:
    name: git bash-completion vi vim repo git-lfs inetutils python

- name: give wheel group sudo powers
  warn: false
  shell: |
    sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
    /usr/sbin/visudo -cf /etc/sudoers
    
    exit 0


