---
- name: make admin user
  vars:
    # created with:
    # openssl passwd -salt saltysalt -1 change_me
    hashed_pw: $1$saltysal$26n01S/ZGnaY.LX7UxFfV/
  user:
    name: admin
    password: "{{ hashed_pw }}"
    groups: wheel
    system: yes
