---
# needed by the software tag
- name: make tmp directory
  file:
    path: /tmp/ansible
    state: directory
    group: nobody
    mode: 0777

- name: upgrade all native packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: upgrade all aur packages
  aur: upgrade=yes use=yay aur_only=yes

- name: install mosquitto
  pacman:
    name: mosquitto

- name: enable mosquitto persistance
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence false'
    line: "persistence true"

- name: set mosquitto persistance locaion
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence_location'
    line: "persistence_location /var/lib/mosquitto/"

- name: enable mosquitto service
  systemd:
    name: mosquitto
    enabled: yes
    masked: no

- name: make software folder
  file:
    path: /opt/software
    state: directory

- name: git config name
  git_config:
    scope: global
    name: user.name
    value: "root"

- name: git config email
  git_config:
    scope: global
    name: user.email
    value: "root@measurebox.local"

- name: git config color
  git_config:
    scope: global
    name: color.ui
    value: "true"

- name: init repo
  command: repo init -u https://github.com/greyltc/manifest.git # -b otter
  args:
    chdir: /opt/software
  when: not ("/opt/software/.repo" is directory)

- name: sync repo
  command: repo sync
  args:
    chdir: /opt/software

- name: set PYTHONPATH
  lineinfile:
    path: /etc/environment
    line: PYTHONPATH=/opt/software/python

# TODO handle our deps in some better way (like with get_deps.sh scripts)
- name: install some deps
  pacman:
    name:  python-systemd python-humanize python-paho-mqtt python-gobject webkit2gtk python-setuptools-scm python-pyserial python-numpy python-scipy python-mpmath

- name: install some aur deps
  aur:
    use: yay
    name: 
      - python-pyvisa
      - python-pyvisa-py
      - python-setuptools-scm-git-archive
      - python-plotly
      - python-dash
      - python-dash-table
#      - python-dash-daq # /usr/lib/python3.8/site-packages/dash-1.13.4-py3.8.egg-info/requires.txt is likely breaking this build
  become: yes
  become_user: aur_builder
  
- name: loosen dash version reqs
  replace:
    path: /usr/lib/python3.8/site-packages/dash-1.13.4-py3.8.egg-info/requires.txt
    after: 'Flask'
    regexp: '=='
    replace: ">="
    before: 'future'
  register: sleep
  when: /usr/lib/python3.8/site-packages/dash-1.13.4-py3.8.egg-info/requires.txt is exists
  
- name: install python-dash-daq
  aur:
    use: yay
    name: 
      - python-dash-daq # /usr/lib/python3.8/site-packages/dash-1.13.4-py3.8.egg-info/requires.txt is likely breaking this build
  become: yes
  become_user: aur_builder
