---
- name: install mosquitto
  pacman:
    name: mosquitto

- name: enable mosquitto persistance
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence false'
    line: "persistence true"

- name: set mosquitto persistance locaion
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence_location'
    line: "persistence_location /var/lib/mosquitto/"

- name: enable mosquitto service
  systemd:
    name: mosquitto
    enabled: yes
    masked: no

- name: make software folder
  file:
    path: /opt/software
    state: directory
    owner: labuser
    group: labuser
    mode: 0775

- name: git config name
  become: yes
  become_user: labuser
  git_config:
    scope: global
    name: user.name
    value: "Lab User"

- name: git config email
  become: yes
  become_user: labuser
  git_config:
    scope: global
    name: user.email
    value: "labuser@measurebox.local"

- name: git config color
  become: yes
  become_user: labuser
  git_config:
    scope: global
    name: color.ui
    value: "true"

- name: init repo
  become: yes
  become_user: labuser
  command: repo init -u https://github.com/greyltc/manifest.git # -b otter
  args:
    chdir: /opt/software
 when: not ("/opt/software/.repo" is directory)

- name: sync repo
  become: yes
  become_user: labuser
  command: repo sync
  args:
    chdir: /opt/software
  

#command: pacman -Q virtualbox-guest-utils
