---
# needed by the software tag
- name: make tmp directory
  file:
    path: /tmp/ansible
    state: directory
    group: nobody
    mode: 0777

- name: upgrade all native packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: upgrade all aur packages
  aur: upgrade=yes use=yay aur_only=yes

- name: install mosquitto
  pacman:
    name: mosquitto

- name: enable mosquitto persistance
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence false'
    line: "persistence true"

- name: set mosquitto persistance locaion
  lineinfile:
    path: /etc/mosquitto/mosquitto.conf
    regexp: '^#persistence_location'
    line: "persistence_location /var/lib/mosquitto/"
    
- name: create mosquitto persistence path
  file:
    path: /var/lib/mosquitto
    state: directory
    owner: mosquitto

- name: enable mosquitto service
  systemd:
    name: mosquitto
    enabled: yes
    masked: no

- name: make software folder
  file:
    path: /opt/software
    state: directory

- name: git config name
  git_config:
    scope: global
    name: user.name
    value: "root"

- name: git config email
  git_config:
    scope: global
    name: user.email
    value: "root@measurebox.local"

- name: git config color
  git_config:
    scope: global
    name: color.ui
    value: "true"

- name: init repo
  command: repo init -u https://github.com/greyltc/manifest.git -b otter
  args:
    chdir: /opt/software
  when: not ("/opt/software/.repo" is directory)

- name: sync repo
  command: repo sync
  args:
    chdir: /opt/software

- name: set PYTHONPATH
  lineinfile:
    path: /etc/environment
    line: PYTHONPATH=/opt/software/python

# TODO handle our deps in some better way (like with get_deps.sh scripts)
- name: install some deps
  pacman:
    state: latest
    name:
      - python-systemd
      - python-humanize
      - python-paho-mqtt
      - python-gobject
      - webkit2gtk 
      - python-setuptools-scm 
      - python-pyserial
      - python-numpy
      - python-scipy 
      - python-mpmath 
      - gnumeric
      - python-pandas

- name: install some aur deps
  aur:
    use: yay
    name: 
      - python-pyvisa
      - python-pyvisa-py
      - python-setuptools-scm-git-archive
      - python-plotly
      - python-boltons
      - python-drawsvg
#      - python-dash
#      - python-dash-table
#      - python-dash-daq # /usr/lib/python3.8/site-packages/dash-1.13.4-py3.8.egg-info/requires.txt is likely breaking this build
  become: yes
  become_user: aur_builder
  
- name: install python-dash-renderer
  shell: |
    set -e
    cd /tmp
    yay -G python-dash-renderer
    cd python-dash-renderer
    #sed -i 's,pkgver=1.8.0,pkgver=1.7.0,g' PKGBUILD # THIS IS A DOWNGRADE!!!
    updpkgsums
    yes | makepkg -Cfi
    rm -rf /tmp/python-dash-renderer
  args:
    executable: /usr/bin/bash
  become: yes
  become_user: aur_builder

#- name: do not upgrade dash-renderer
#  shell: |
#    set -e
#    sed '/^\[options\].*/a IgnorePkg = python-dash-renderer' -i /etc/pacman.conf
#  args:
#    executable: /usr/bin/bash
#    warn: false

- name: install python-dash-html-components
  shell: |
    set -e
    cd /tmp
    yay -G python-dash-html-components
    cd python-dash-html-components
    #sed -i 's,pkgver=1.0.3,pkgver=1.1.0,g' PKGBUILD
    updpkgsums
    yes | makepkg -Cfi
    rm -rf /tmp/python-dash-html-components
  args:
    executable: /usr/bin/bash
  become: yes
  become_user: aur_builder

- name: install python-dash-core-components
  shell: |
    set -e
    cd /tmp
    yay -G python-dash-core-components
    cd python-dash-core-components
    #sed -i 's,pkgver=1.10.1,pkgver=1.11.0,g' PKGBUILD
    updpkgsums
    yes | makepkg -Cfi
    rm -rf /tmp/python-dash-core-components
  args:
    executable: /usr/bin/bash
  become: yes
  become_user: aur_builder

- name: install some final dash deps
  aur:
    use: yay
    name: 
      - python-flask
      - python-flask-compress
      - python-flask-seasurf
      - python-future
  become: yes
  become_user: aur_builder

- name: install python-dash
  shell: |
    set -e
    cd /tmp
    yay -G python-dash
    cd python-dash
    #sed -i 's,pkgver=1.15.0,pkgver=1.16.1,g' PKGBUILD
    updpkgsums
    yes | makepkg -Cfi
    rm -rf /tmp/python-dash
  args:
    executable: /usr/bin/bash
  become: yes
  become_user: aur_builder

- name: fix for dash-table version does not exist
  replace:
    path: /usr/lib/python3.8/site-packages/dash-1.16.1-py3.8.egg-info/requires.txt
    after: 'dash-table'
    regexp: '4.10.1'
    replace: "4.10.0"
    before: 'future'
  when: "'/usr/lib/python3.8/site-packages/dash-1.16.1-py3.8.egg-info/requires.txt' is file"

- name: install python-dash-daq
  aur:
    use: yay
    name: 
      - python-dash-daq
  become: yes
  become_user: aur_builder
