---
- name: software setup
  hosts: localhost
  become: yes
  tasks:
    - import_role:
       name: baseline
    - import_role:
       name: aur
    - import_role:
       name: aur-phase2
    - import_role:
       name: vagrant
    - import_role:
       name: desktop
