---
- name: software setup
  hosts: localhost
  become: yes
  tasks:
    - import_role:
       name: baseline
    - import_role:
       name: aur
    - import_role:
       name: vagrant
    - import_role:
       name: desktop
    - import_role:
       name: labuser
#    - import_role:
#       name: reboot
