---
- name: install the desktop environment
  pacman:
    name: gdm gnome

- name: prevent sleep at login screen
  shell: unset XDG_RUNTIME_DIR; dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing

- name: screensaver does not activate
  lineinfile:
    path: /usr/share/glib-2.0/schemas/org.gnome.desktop.screensaver.gschema.xml
    insertafter: 'name="idle-activation-enabled"'
    regexp: '<default>'
    line: "      <default>trfde</default>"

#- name: set various config defaults
#  shell: |
#    sed -i '/name="idle-activation-enabled"/,/<\/key>/{s|<default>true<\/default>|<default>false</default>|}' /usr/share/glib-2.0/schemas/org.gnome.desktop.screensaver.gschema.xml
#    sed -i '/name="lock-enabled"/,/<\/key>/{s|<default>true<\/default>|<default>false</default>|}' /usr/share/glib-2.0/schemas/org.gnome.desktop.screensaver.gschema.xml
#    sed -i '/name="idle-delay"/,/<\/key>/{s|<default>300<\/default>|<default>0</default>|}' /usr/share/glib-2.0/schemas/org.gnome.desktop.session.gschema.xml
#    sed -i '/name="sleep-inactive-ac-timeout"/,/<\/key>/{s|<default>1200<\/default>|<default>0</default>|}' /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.power.gschema.xml
#    glib-compile-schemas .
#  args:
#    chdir: /usr/share/glib-2.0/schemas
#    warn: no

- name: make autologin group
  group:
    name: autologin
    system: yes
    state: present

- name: make nopasswdlogin group
  group:
    name: nopasswdlogin
    system: yes
    state: present
