---
- name: Check if virtualbox-guest-utils is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_installed
  failed_when: no
  changed_when: no

- name: Check if virtualbox-guest-utils-nox is installed
  command: pacman -Q virtualbox-guest-utils
  register: virtualbox_guest_utils_nox_installed
  failed_when: no
  changed_when: no

- name: install linux-firmware
  pacman:
    name: linux-firmware
  when: virtualbox_guest_utils_installed.rc == 0 or virtualbox_guest_utils_nox_installed.rc == 0

- name: Determine available groups
  getent:
    database: group

- name: add vagrant to the aur group
  user:
    name: vagrant
    append: yes
    groups: aur
  when: ("/vagrant" is directory) and "'aur' in getent_group"

- name: add vagrant to some other groups and make sure system user
  user:
    name: vagrant
    append: yes
    groups: video,vboxsf,users,uucp,tty
    system: yes
  when: ( virtualbox_guest_utils_nox_installed.rc == 0 or virtualbox_guest_utils_installed.rc == 0 ) and "'vagrant' in getent_passwd"

- name: install vagrant public ssh key
  get_url:
    url: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    mode: '0600'
    force: yes
  become: yes
  become_user: vagrant
