---
- name: install linux-firmware
  pacman:
    name: linux-firmware

- name: Determine available groups
  getent:
    database: group

- name: add vagrant to the aur group
  user:
    name: vagrant
    append: yes
    groups: aur
  when: "'aur' in getent_group"

- name: add vagrant to some other groups nad make sure system user
  user:
    name: vagrant
    append: yes
    groups: video,vboxsf,users,uucp,tty
    system: yes

