---
- name: install git and base devel group
  pacman:
    name: linux-firmware

- name: Determine available groups
  getent:
    database: group



when: aur in ansible_facts.getent_group



- name: make mutovis user
  vars:
    # created with:
    # openssl passwd -salt saltysalt -1 the_password
    hashed_pw: $1$saltysal$.QPThK.tBENRwBZL1fD5I1 
  user:
    name: mutovis
    password: "{{ hashed_pw }}"
    system: yes
    groups: ['uucp', 'gpib']

when: ansible in ansible_facts.getent_passwd
