---
- name: aur_helper folder clean A
  file:
    path: /home/aur_helper/.cache
    state: absent

- name: remake aur_helper .cache
  file:
    path: /home/aur_helper/.cache
    state: directory

- name: aur_helper folder clean B
  file:
    path: /home/aur_helper/.yarn
    state: absent

- name: clean yay folder
  file:
    path: /home/labuser/.cache/yay
    state: absent

- name: clean history A
  shell: history -r
  ignore_errors: yes
  args:
    executable: /usr/bin/bash

- name: clean history B
  shell: history -r
  ignore_errors: yes
  become: yes
  become_user: vagrant
  args:
    executable: /usr/bin/bash

- name: clean history C
  shell: history -r
  ignore_errors: yes
  become: yes
  become_user: admin
  args:
    executable: /usr/bin/bash

- name: clean history D
  shell: history -r
  ignore_errors: yes
  become: yes
  become_user: labuser
  args:
    executable: /usr/bin/bash

#- name: clean history
#  shell: history -r
#  file:
#    path: /home/vagrant/.bash_history
#    state: absent

- name: clean pacman packages
  shell: yes | pacman -Scc

- name: clean aur packages
  shell: yes | pacman -Scc --cachedir /var/cache/makepkg/pkg

- name: clean journal A
  shell: journalctl --rotate

- name: clean journal B
  shell: journalctl --vacuum-time=1s
