---
- name: aur_helper folder clean
  file:
    path: /home/aur_helper/.cache
    state: absent

- name: remake aur_helper .cache
  file:
    path: /home/aur_helper/.cache
    state: directory

- name: aur_helper folder clean
  file:
    path: /home/aur_helper/.yarn
    state: absent

- name: clean yay folder
  file:
    path: /home/labuser/.cache/yay
    state: absent

- name: clean history
  file:
    path: /home/labuser/.bash_history
    state: absent

- name: clean history
  file:
    path: /home/vagrant/.bash_history
    state: absent

- name: clean history
  file:
    path: /home/admin/.bash_history
    state: absent

- name: clean history
  file:
    path: /home/labuser/.bash_history
    state: absent

- name: clean pacman packages
  shell: yes | pacman -Scc

- name: clean aur packages
  shell: yes | pacman -Scc --cachedir /var/cache/makepkg/pkg
