---
- name: aur_helper folder clean
  file:
    path: /home/aur_helper/.cache
    state: absent

- name: remake aur_helper .cache
  file:
    path: /home/aur_helper/.cache
    state: directory

- name: aur_helper folder clean
  file:
    path: /home/aur_helper/.yarn
    state: absent

- name: clean yay folder
  file:
    path: /home/labuser/.cache/yay
    state: absent

#- name: find pacman packages
#  find:
#    paths: /etc/Ansible
#  register: files_to_delete

#- name: delete pacman packages
#  file:
#    path: "{{ item.path }}"
#    state: absent
#  with_items: "{{ files_to_delete.files }}"
    
- name: clean pacman packages
  pacman:
    extra_args: '-Scc'

- name: clean aur packages
  pacman:
    extra_args: '-Scc --cachedir /var/cache/makepkg/pkg'
