---
- name: install git and base devel group and go for yay
  pacman:
    name: base-devel git go

- name: make aur group
  group:
    name: aur
    system: yes
    state: present

- name: make aur_builder user
  user:
    name: aur_builder
    groups: wheel,aur

- name: give aur_builder install perms
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: make pkgdest
  file:
    path: /var/cache/makepkg/pkg
    state: directory
    group: aur
    mode: 0775

- name: set pkgdest
  shell: sed -i "s,^#PKGDEST=.*,PKGDEST=/var/cache/makepkg/pkg,g" /etc/makepkg.conf
  args:
    warn: no

- name: build zst
  shell: sed -i "s,^PKGEXT=.*,PKGEXT='.pkg.tar.zst',g" /etc/makepkg.conf
  args:
    warn: no

- name: Check if ansible aur module is installed
  command: pacman -Q ansible-aur-git
  register: check_install
  failed_when: no
  changed_when: no

- name: clone ansible-aur-git repo from the AUR
  git:
    repo: 'https://aur.archlinux.org/ansible-aur-git.git'
    dest: /home/aur_builder/ansible-aur-git
  when: check_install.rc != 0
  become: yes
  become_user: aur_builder

- name: build and install ansible AUR module
  command: "makepkg -Cfi --noconfirm"
  args:
    chdir: /home/aur_builder/ansible-aur-git
  become: yes
  become_user: aur_builder
  when: check_install.rc != 0
  
- name: ansible AUR module cleanup
  file:
    path: /home/aur_builder/ansible-aur-git
    state: absent
